[workspace]

members = [
    "kml_net_tensor",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Small machine learning library"

[workspace.dependencies]

